name: Deploy Frontend to Oracle Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      RELEASE_NAME: ${{ github.run_id }}_${{ github.run_number }}
      REMOTE_PATH: /var/www/releases
      CURRENT_PATH: /var/www/current

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Create release directory on Oracle server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_KEY }}
          port: 22
          script: |
            sudo mkdir -p $REMOTE_PATH/$RELEASE_NAME
            sudo chown -R ${{ secrets.ORACLE_USER }}:${{ secrets.ORACLE_USER }} $REMOTE_PATH

      - name: Upload build folder to Oracle server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_KEY }}
          port: 22
          source: "build/*"
          target: "$REMOTE_PATH/${{ env.RELEASE_NAME }}"
          strip_components: 1

      - name: Update current symlink to new release
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.ORACLE_HOST }}
          username: ${{ secrets.ORACLE_USER }}
          key: ${{ secrets.ORACLE_KEY }}
          port: 22
          script: |
            sudo ln -sfn $REMOTE_PATH/$RELEASE_NAME $CURRENT_PATH
            echo "✅ Deployed release: $RELEASE_NAME"
